# Generated by Django 5.2.6 on 2025-10-16 08:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Mobile Legends', 'Mobile Legends'), ('PUBG Mobile', 'PUBG Mobile')], max_length=50)),
                ('nama_paket', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('Diamonds', 'Diamonds'), ('UC', 'UC')], default='Diamonds', max_length=50)),
                ('deskripsi', models.TextField(blank=True, help_text='Contoh: Bonus 10 Diamonds, Proses 1-5 Menit, dll.', null=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='topup_images/')),
            ],
        ),
        migrations.CreateModel(
            name='AkunGaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_akun', models.CharField(max_length=100)),
                ('game', models.CharField(choices=[('Mobile Legends', 'Mobile Legends'), ('PUBG Mobile', 'PUBG Mobile'), ('Genshin Impact', 'Genshin Impact'), ('Haikyuu', 'Haikyuu'), ('Black Desert', 'Black Desert')], max_length=50)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(blank=True, help_text='Ini akan menjadi gambar utama atau thumbnail.', null=True, upload_to='akun_images/')),
                ('is_unggulan', models.BooleanField(default=False, help_text='Tandai jika ini adalah akun unggulan untuk ditampilkan di landing page.')),
                ('is_sold', models.BooleanField(default=False)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('akun_email', models.CharField(blank=True, max_length=255, null=True)),
                ('akun_password', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('highlight', models.TextField(blank=True, help_text='Isi dengan poin-poin utama, pisahkan dengan baris baru (Enter).', null=True)),
                ('favorit', models.ManyToManyField(blank=True, related_name='akun_favorit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GambarAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='akun_images/tambahan/')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_tambahan', to='main.akungaming')),
            ],
        ),
        migrations.CreateModel(
            name='Kupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('diskon_persen', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('aktif', models.BooleanField(default=True)),
                ('digunakan_oleh', models.ManyToManyField(blank=True, related_name='kupon_yang_digunakan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tanggal_pembelian', models.DateTimeField(auto_now_add=True)),
                ('harga_pembelian', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('VERIFYING', 'Verifikasi Pembayaran'), ('COMPLETED', 'Selesai'), ('CANCELED', 'Dibatalkan')], default='PENDING', max_length=10)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/')),
                ('midtrans_token', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ulasan', models.TextField(blank=True, null=True)),
                ('harga_asli', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('akun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.akungaming')),
                ('kupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kupon')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopUpPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tanggal_pembelian', models.DateTimeField(auto_now_add=True)),
                ('harga_pembelian', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('COMPLETED', 'Selesai'), ('CANCELED', 'Dibatalkan')], default='PENDING', max_length=10)),
                ('midtrans_token', models.CharField(blank=True, max_length=255, null=True)),
                ('harga_asli', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('game_user_id', models.CharField(max_length=100)),
                ('game_zone_id', models.CharField(blank=True, max_length=50, null=True)),
                ('kupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kupon')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.topupproduct')),
            ],
        ),
    ]
