# Generated by Django 5.2.6 on 2025-09-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkunGaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_akun', models.CharField(max_length=100)),
                ('game', models.CharField(choices=[('Mobile Legends', 'Mobile Legends'), ('PUBG Mobile', 'PUBG Mobile'), ('Genshin Impact', 'Genshin Impact'), ('Valorant', 'Valorant')], max_length=50)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='akun_images/')),
                ('is_unggulan', models.BooleanField(default=False, help_text='Tandai jika ini adalah akun unggulan untuk ditampilkan di landing page.')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
