# Generated by Django 5.2.6 on 2025-09-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_akungaming_penjual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akungaming',
            name='penjual',
        ),
    ]
