# Generated by Django 5.2.6 on 2025-09-29 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_akungaming_penjual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='akungaming',
            name='favorit',
            field=models.ManyToManyField(blank=True, related_name='akun_favorit', to=settings.AUTH_USER_MODEL),
        ),
    ]
