# Generated by Django 5.2.6 on 2025-09-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_akungaming_favorit'),
    ]

    operations = [
        migrations.AddField(
            model_name='akungaming',
            name='kd_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='akungaming',
            name='kills',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='akungaming',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='akungaming',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
