# Generated by Django 5.2.6 on 2025-09-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_akungaming_kd_ratio_akungaming_kills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akungaming',
            name='gambar',
            field=models.ImageField(blank=True, help_text='Ini akan menjadi gambar utama atau thumbnail.', null=True, upload_to='akun_images/'),
        ),
        migrations.CreateModel(
            name='GambarAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='akun_images/tambahan/')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_tambahan', to='main.akungaming')),
            ],
        ),
    ]
