# Generated by Django 5.2.6 on 2025-09-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_akungaming_gambar_gambarakun'),
    ]

    operations = [
        migrations.AddField(
            model_name='akungaming',
            name='highlight',
            field=models.TextField(blank=True, help_text='Isi dengan poin-poin utama, pisahkan dengan baris baru (Enter).', null=True),
        ),
    ]
