# Generated by Django 5.2.6 on 2025-09-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_akungaming_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akungaming',
            name='game',
            field=models.CharField(choices=[('Mobile Legends', 'Mobile Legends'), ('PUBG Mobile', 'PUBG Mobile'), ('Genshin Impact', 'Genshin Impact'), ('Haikyuu', 'Haikyuu'), ('Black Desert', 'Black Desert')], max_length=50),
        ),
    ]
