# Generated by Django 5.2.6 on 2025-09-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_akungaming_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akungaming',
            name='kd_ratio',
        ),
        migrations.RemoveField(
            model_name='akungaming',
            name='kills',
        ),
        migrations.RemoveField(
            model_name='akungaming',
            name='views',
        ),
    ]
