# Generated by Django 5.2.6 on 2025-09-29 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_akungaming_kd_ratio_remove_akungaming_kills_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='akungaming',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tanggal_pembelian', models.DateTimeField(auto_now_add=True)),
                ('harga_pembelian', models.DecimalField(decimal_places=2, max_digits=10)),
                ('akun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.akungaming')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
