# Generated by Django 5.2.6 on 2025-09-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_akungaming_is_sold_pembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='akungaming',
            name='akun_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='akungaming',
            name='akun_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('VERIFYING', 'Verifikasi Pembayaran'), ('COMPLETED', 'Selesai'), ('CANCELED', 'Dibatalkan')], default='PENDING', max_length=10),
        ),
    ]
