# Generated by Django 5.2.6 on 2025-09-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_akungaming_akun_email_akungaming_akun_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='midtrans_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
