# Generated by Django 5.2.6 on 2025-09-30 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pembelian_midtrans_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='ulasan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
