# Generated by Django 5.2.6 on 2025-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_kupon_pembelian_harga_asli_pembelian_kupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembelian',
            old_name='midtrans_token',
            new_name='xendit_invoice_id',
        ),
        migrations.AddField(
            model_name='pembelian',
            name='xendit_invoice_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
