# Generated by Django 5.2.6 on 2025-10-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_midtrans_token_pembelian_xendit_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kupon',
            name='midtrans_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
