# Generated by Django 5.2.6 on 2025-10-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_kupon_midtrans_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembelian',
            old_name='xendit_invoice_id',
            new_name='midtrans_token',
        ),
        migrations.RemoveField(
            model_name='kupon',
            name='midtrans_token',
        ),
        migrations.RemoveField(
            model_name='pembelian',
            name='xendit_invoice_url',
        ),
    ]
