# Generated by Django 5.2.6 on 2025-10-15 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_xendit_invoice_id_pembelian_midtrans_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Mobile Legends', 'Mobile Legends'), ('PUBG Mobile', 'PUBG Mobile')], max_length=50)),
                ('nama_paket', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='topup_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TopUpPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tanggal_pembelian', models.DateTimeField(auto_now_add=True)),
                ('harga_pembelian', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('COMPLETED', 'Selesai'), ('CANCELED', 'Dibatalkan')], default='PENDING', max_length=10)),
                ('midtrans_token', models.CharField(blank=True, max_length=255, null=True)),
                ('game_user_id', models.CharField(max_length=100)),
                ('game_zone_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.topupproduct')),
            ],
        ),
    ]
