# Generated by Django 5.2.6 on 2025-10-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_topupproduct_topuppembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupproduct',
            name='deskripsi',
            field=models.TextField(blank=True, help_text='Contoh: Bonus 10 Diamonds, Proses 1-5 Menit, dll.', null=True),
        ),
        migrations.AddField(
            model_name='topupproduct',
            name='kategori',
            field=models.CharField(choices=[('Diamonds', 'Diamonds'), ('UC', 'UC')], default='Diamonds', max_length=50),
        ),
    ]
