# Generated by Django 5.2.6 on 2025-10-15 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_topupproduct_deskripsi_topupproduct_kategori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kupon',
            name='digunakan_oleh',
            field=models.ManyToManyField(blank=True, related_name='kupon_yang_digunakan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topuppembelian',
            name='harga_asli',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='topuppembelian',
            name='kupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kupon'),
        ),
    ]
